# Generated by Django 4.1.3 on 2023-07-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_set',
            fields=[
                ('word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('sen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('pswd', models.CharField(max_length=255)),
                ('utype', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('repl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repl_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='RepDetail',
            fields=[
                ('repdet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('det', models.CharField(max_length=255)),
                ('rep', models.CharField(max_length=255)),
                ('repl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.replacement')),
            ],
        ),
        migrations.CreateModel(
            name='Paraphrase',
            fields=[
                ('para_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('para_at', models.DateTimeField(auto_now_add=True)),
                ('txt', models.TextField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParaDetail',
            fields=[
                ('paradet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('det', models.CharField(max_length=255)),
                ('rep', models.CharField(max_length=255)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.paraphrase')),
            ],
        ),
    ]
