# Generated by Django 4.1.3 on 2023-11-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_dataset_filtered_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('syno_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('syno_word', models.CharField(max_length=255)),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.word')),
            ],
        ),
    ]
