# Generated by Django 4.1.3 on 2023-12-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_word_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=255),
        ),
    ]
