# Generated by Django 4.1.3 on 2023-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=255),
        ),
    ]
