# Generated by Django 4.1.3 on 2023-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_user_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(choices=[(True, 'Verified'), (False, 'Not Verified')], default=False),
        ),
    ]
