# Generated by Django 4.1.3 on 2023-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(choices=[(1, 'Verified'), (0, 'Not Verified')], default=False),
        ),
    ]
