# Generated by Django 4.1.3 on 2023-12-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_user_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Synonyms',
        ),
    ]
