# Generated by Django 4.1.3 on 2023-04-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_set',
            fields=[
                ('word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('sen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('utype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('rep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rep_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='RepDetail',
            fields=[
                ('repdet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('det_word', models.CharField(max_length=255)),
                ('rep_word', models.CharField(max_length=255)),
                ('rep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.replacement')),
            ],
        ),
        migrations.CreateModel(
            name='Paraphrase',
            fields=[
                ('para_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('para_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParaDetail',
            fields=[
                ('paradet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('det_word', models.CharField(max_length=255)),
                ('rep_word', models.CharField(max_length=255)),
                ('para_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paraphrase')),
            ],
        ),
    ]
