# Generated by Django 4.1.3 on 2023-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_password_user_pswd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradetail',
            old_name='det_word',
            new_name='det',
        ),
        migrations.RenameField(
            model_name='paradetail',
            old_name='rep_word',
            new_name='rep',
        ),
        migrations.RenameField(
            model_name='repdetail',
            old_name='det_word',
            new_name='det',
        ),
        migrations.RenameField(
            model_name='repdetail',
            old_name='rep_word',
            new_name='rep',
        ),
    ]
