# Generated by Django 4.1.3 on 2023-04-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_det_word_paradetail_det_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradetail',
            old_name='para_id',
            new_name='para',
        ),
        migrations.RenameField(
            model_name='paraphrase',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='repdetail',
            old_name='rep_id',
            new_name='repl',
        ),
        migrations.RenameField(
            model_name='replacement',
            old_name='rep_at',
            new_name='repl_at',
        ),
        migrations.RenameField(
            model_name='replacement',
            old_name='rep_id',
            new_name='repl_id',
        ),
        migrations.RenameField(
            model_name='replacement',
            old_name='user_id',
            new_name='user',
        ),
    ]
