# Generated by Django 4.1.3 on 2023-05-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_para_id_paradetail_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
