# Generated by Django 4.1.3 on 2023-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_paraphrase_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paraphrase',
            name='txt',
            field=models.TextField(default=None, null=True),
        ),
    ]
