# Generated by Django 4.2.4 on 2023-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_paraphrase_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_set',
            name='gen',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
